const queries = new Map([
    ["Ipsilateral Impact", [
        {
            id: 0,
            parametor: "Trial",
            comparator: "==",
            value: "Straight Line",
            abs: "None",
        },
        {
            id: 1,
            parametor: "Blocks",
            comparator: "==",
            value: "Null",
            abs: "None",
        },
        {
            id: 2,
            parametor: "Fore Strides",
            comparator: ">=",
            value: "20",
            abs: "None",
        },
        {
            id: 3,
            parametor: "Fore Signed Vector Sum",
            comparator: ">",
            value: "8.5",
            abs: "Right",
        },
        {
            id: 4,
            parametor: "Hind Diff Min Mean",
            comparator: ">",
            value: "3",
            abs: "Right",
        },
        {
            id: 5,
            parametor: "Hind Diff Min Mean",
            comparator: "Same Signs",
            value: "Fore Diff Min Mean",
            abs: "None",
        }
    ]],
    ["Ipsilateral Pushoff", [
        {
            id: 0,
            parametor: "Trial",
            comparator: "==",
            value: "Straight Line",
            abs: "None",
        },
        {
            id: 1,
            parametor: "Blocks",
            comparator: "==",
            value: "Null",
            abs: "None",
        },
        {
            id: 2,
            parametor: "Fore Strides",
            comparator: ">=",
            value: "20",
            abs: "None",
        },
        {
            id: 3,
            parametor: "Fore Signed Vector Sum",
            comparator: ">",
            value: "8.5",
            abs: "Right",
        },
        {
            id: 4,
            parametor: "Hind Diff Max Mean",
            comparator: ">",
            value: "3",
            abs: "Right",
        },
        {
            id: 5,
            parametor: "Hind Diff Max Mean",
            comparator: "Same Signs",
            value: "Fore Diff Min Mean",
            abs: "None",
        }
    ]],
    ["Just Impact", [
        {
            id: 0,
            parametor: "Trial",
            comparator: "==",
            value: "Straight Line",
            abs: "None",
        },
        {
            id: 1,
            parametor: "Blocks",
            comparator: "==",
            value: "Null",
            abs: "None",
        },
        {
            id: 2,
            parametor: "Fore Strides",
            comparator: ">=",
            value: "20",
            abs: "None",
        },
        {
            id: 3,
            parametor: "Fore Signed Vector Sum",
            comparator: "<",
            value: "8.5",
            abs: "Right",
        },
        {
            id: 4,
            parametor: "Hind Diff Min Mean",
            comparator: ">",
            value: "3",
            abs: "Right",
        },
        {
            id: 6,
            parametor: "Hind Diff Min Mean",
            comparator: "Same Signs",
            value: "Fore Diff Min Mean",
            abs: "None",
        },
    ]],
    ["Just Pushoff", [
        {
            id: 0,
            parametor: "Trial",
            comparator: "==",
            value: "Straight Line",
            abs: "None",
        },
        {
            id: 1,
            parametor: "Blocks",
            comparator: "==",
            value: "Null",
            abs: "None",
        },
        {
            id: 2,
            parametor: "Fore Strides",
            comparator: ">=",
            value: "20",
            abs: "None",
        },
        {
            id: 3,
            parametor: "Fore Signed Vector Sum",
            comparator: "<",
            value: "8.5",
            abs: "Right",
        },
        {
            id: 4,
            parametor: "Hind Diff Max Mean",
            comparator: ">",
            value: "3",
            abs: "Right",
        },
        {
            id: 6,
            parametor: "Hind Diff Max Mean",
            comparator: "Same Signs",
            value: "Fore Diff Min Mean",
            abs: "None",
        },
    ]]
]);

export default queries;